apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.name }}
spec:
  type: ClusterIP
  ports:
  - name: socket
    port: 9998
    protocol: TCP 
  selector:
    app: {{ .Values.proxy.name }}
