stages:
  - sonarqube
  - build
  - release_helm
#  - deploy_k8s_test
  - clean

include:
  # initialize 
  - project: "ehr/dev-ops/gitlab-cis"
    file: ".gitlab-ci-docker-init.yml"

  # Sonarqube test
  - project: "ehr/dev-ops/gitlab-cis"
    file: ".gitlab-ci-test-sonarqube.yml"

variables:
  DEV_PROXY_IMAGE: $CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_REF_NAME
  DEV_REDIS_SENTINEL_IMAGE: $CI_REGISTRY_IMAGE/redis:$CI_COMMIT_REF_NAME

build:
  stage: build
  only:
    - /^version-.*$/
  script:
    - echo Building version $GIT_SEMVER
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest_proxy || true
    - docker pull $CI_REGISTRY_IMAGE:latest_redis || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest_proxy --build-arg GIT_SEMVER=${GIT_SEMVER} --tag $DEV_PROXY_IMAGE --tag $CI_REGISTRY_IMAGE:latest_proxy ./proxy
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest_redis --build-arg GIT_SEMVER=${GIT_SEMVER} --tag $DEV_REDIS_SENTINEL_IMAGE --tag $CI_REGISTRY_IMAGE:latest_redis ./redis
    - docker push $DEV_PROXY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:latest_proxy
    - docker push $DEV_REDIS_SENTINEL_IMAGE
    - docker push $CI_REGISTRY_IMAGE:latest_redis

helm:
  stage: release_helm
  image:
    name: dtzar/helm-kubectl:3.0.1
  only:
    - /^version-.*$/
  script:
    # Extract version (numbers only) from commit tag
    - SEMVER=`echo $CI_COMMIT_REF_NAME | sed 's/.*-\(.*\)/\1/'`
    # Set install image in values file
    - sed -i "s~__CI_REGISTRY_REDIS_IMAGE__~${DEV_REDIS_SENTINEL_IMAGE}~" redis-sentinel-proxy-charm/values.yaml
    - sed -i "s~__CI_REGISTRY_PROXY_IMAGE__~${DEV_PROXY_IMAGE}~" redis-sentinel-proxy-charm/values.yaml
    - sed -i "s~__APPVERSION__~${CI_COMMIT_REF_NAME}~" redis-sentinel-proxy-charm/Chart.yaml
    # Debugging aid to show how variables got replaced...
    - echo "---------------------------------"
    - cat redis-sentinel-proxy-charm/Chart.yaml
    - echo "---------------------------------"
    - cat redis-sentinel-proxy-charm/values.yaml
    - echo "---------------------------------"
    # Build chart and upload to our ChartMuseum
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm repo add chartmuseum $CHM_URL --username $CHM_USER --password $CHM_PASS
    - helm push ./helm --version=$SEMVER chartmuseum
