stages:
  - sonarqube
  - build
  - release_helm
  #  - deploy_k8s_test
  - clean

include:
  # initialize 
  - project: "ehr/dev-ops/gitlab-cis"
    file: ".gitlab-ci-docker-init.yml"

  # Sonarqube test
  # org.sonar.java.AnalysisException: Please provide compiled classes of your project with sonar.java.binaries property
  #  - project: "ehr/dev-ops/gitlab-cis"
  #    file: ".gitlab-ci-test-sonarqube.yml"

  # Build docker release container
  - project: "ehr/dev-ops/gitlab-cis"
    file: ".gitlab-ci-docker-build.yml"

  # Release Helm.
  - project: "ehr/dev-ops/gitlab-cis"
    file: ".gitlab-ci-k8s-helm.yml"

  # deploy to k8s test
  #  - project: "ehr-test-group/dev-ops/gitlab-cis"
  #    file: ".gitlab-ci-k8s-test-deploy.yml"

  # Clean gitlab docker registry keep only 5
  - project: "ehr/dev-ops/gitlab-cis"
    file: ".gitlab-ci-registry-cleaner.yml"
