namespace: redis-sentinel-proxy

sentinel:
  name: sentinel
  replicas: 3
  repository: __CI_REGISTRY_REDIS_IMAGE__
  imagePullPolicy: Always

redis:
  name: redis
  replicas: 3
  repository: __CI_REGISTRY_REDIS_IMAGE__
  imagePullPolicy: Always

proxy:
  name: proxy
  replicas: 1
  repository: __CI_REGISTRY_PROXY_IMAGE__
  imagePullPolicy: Always

values:
  redisName: redis
  sentinelPort: 26379
  sentinelService: sentinel