create or replace PACKAGE PKG_REDIS AS
    HOST VARCHAR2(128) := 'http://192.168.21.200:31221/api/';

    BUILDING_CODE_COMMAND VARCHAR2(13) := 'BUILDING_CODE';
    UTILITY_BUILDING_CODE_COMMAND VARCHAR2(21) := 'UTILITY_BUILDING_CODE';
    PROCEDURE_CODE_COMMAND VARCHAR2(14) := 'PROCEDURE_CODE';
    DOCUMENT_CODE_COMMAND VARCHAR2(13) := 'DOCUMENT_CODE';
    
    BUILDING_API VARCHAR2(128) := HOST || 'building';
    UTILITY_BUILDING_API VARCHAR2(128) := HOST || 'utilitybuilding';
    PROCEDURE_API VARCHAR2(128) := HOST || 'procedure';
    DOCUMENT_API VARCHAR2(128) := HOST || 'document/';

    FUNCTION REDIS_API_REQUEST
    (
        COMMAND IN VARCHAR2
    )
    RETURN VARCHAR2;

    FUNCTION GET_EHR_CODE
    (
        BUIDLING_TYPE NUMBER
    )
    RETURN VARCHAR2;
    
    FUNCTION GET_PROCEDURE_CODE
    RETURN VARCHAR2;
    
    FUNCTION GET_DOCUMENT_CODE
    (
        DOTY_ID NUMBER
    )
    RETURN VARCHAR2;
    
END PKG_REDIS;