#ifndef MAINMODULE_H_
#define MAINMODULE_H_

#include <time.h>
#include <stdlib.h>
#include <string.h>

#include "redismodule.h"

//keys names
#define EHR_CODE_SET_KEY "EHR_CODE_SET_KEY"
#define PROCEDURE_KEY "PROCEDURE_KEY"
#define DOCUMENT_KEY "DOCUMENT_KEY"
#define YEAR_KEY "YEAR_KEY"

//fields names
#define EHR_CODE_SET_UTILITY_BUILDING_FIELD "EHR_CODE_SET_UTILITY_BUILDING_FIELD"
#define EHR_CODE_SET_BUILDING_FIELD "EHR_CODE_SET_BUILDING_FIELD"

//Module name, version and call name
#define BUILDING_MODULE "BUILDING_MODULE"
#define BUILDING_MODULE_VERSION 1
#define BUILDING_MODULE_COMMAND "BUILDING_CODE"

#define UTILITY_BUILDING_MODULE "UTILITY_BUILDING_MODULE"
#define UTILITY_BUILDING_MODULE_VERSION 1
#define UTILITY_BUILDING_MODULE_VERSION_COMMAND "UTILITY_BUILDING_CODE"

#define PROCEDURE_MODULE "PROCEDURE_MODULE"
#define PROCEDURE_MODULE_VERSION 1
#define PROCEDURE_MODULE_VERSION_COMMAND "PROCEDURE_CODE"

#define YEAR_MODULE "YEAR_MODULE"
#define YEAR_MODULE_VERSION 1
#define YEAR_MODULE_COMMAND "YEAR"

#define DOCUMENT_MODULE "DOCUMENT_MODULE"
#define DOCUMENT_MODULE_VERSION 1
#define DOCUMENT_MODULE_COMMAND "DOCUMENT_CODE"

#define EXIST_ERROR "Value doesn't not exist!"

int command(RedisModuleCtx *, RedisModuleString **, int);

#endif