apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - name: socket
    port: 9999
    nodePort: 31222
    protocol: TCP 
  - name: http
    port: 8080
    nodePort: 8090
    protocol: TCP 
  selector:
    app: {{ .Values.proxy.name }}
