apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ehrProxy.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api/redis/v1
        backend:
          serviceName: {{ .Values.proxy.name }}
          servicePort: 8080
  tls:
  - secretName: {{ .Values.ingress.tlsSecret }}
    hosts:
      - {{ .Values.ingress.host }}