apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ehrProxy.name }}
spec:
  type: ClusterIP
  ports:
  - name: socket
    port: 9999
    protocol: TCP 
  - name: http
    port: 8080
    protocol: TCP 
  selector:
    app: {{ .Values.ehrProxy.name }}
