apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
spec:
  ports:
  - containerPort: 
    port: 6379
    name: {{ .Values.redis.name }}
  clusterIP: None
  selector:
    app: {{ .Values.redis.name }}
