apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.redis.name }}
data:
  redis_master_conf: |
    bind 0.0.0.0
    port 6379
    loadmodule ./out/so/yearmodule.so
    loadmodule ./out/so/buildingmodule.so
    loadmodule ./out/so/documentmodule.so
    loadmodule ./out/so/proceduremodule.so
    loadmodule ./out/so/utilitybuildingmodule.so
    save ""
    appendonly no
    maxmemory 1gb
    maxmemory-policy noeviction
    timeout 0
    tcp-keepalive 300
    tcp-backlog 512

    #disabled
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command KEYS ""
    rename-command PEXPIRE ""
    rename-command DEL ""
    rename-command SHUTDOWN ""
    rename-command BGREWRITEAOF ""
    rename-command BGSAVE ""
    rename-command SAVE ""
    rename-command SPOP ""
    rename-command SREM ""
    rename-command RENAME ""
  redis_slave_conf: |
    bind 0.0.0.0
    port 6379
    replicaof redis 6379
    loadmodule ./out/so/yearmodule.so
    loadmodule ./out/so/buildingmodule.so
    loadmodule ./out/so/documentmodule.so
    loadmodule ./out/so/proceduremodule.so
    loadmodule ./out/so/utilitybuildingmodule.so
    save ""
    appendonly no
    maxmemory 1gb
    maxmemory-policy noeviction
    replica-serve-stale-data no
    timeout 0
    tcp-keepalive 300
    tcp-backlog 512

    #disabled
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command KEYS ""
    rename-command PEXPIRE ""
    rename-command DEL ""
    rename-command SHUTDOWN ""
    rename-command BGREWRITEAOF ""
    rename-command BGSAVE ""
    rename-command SAVE ""
    rename-command SPOP ""
    rename-command SREM ""
    rename-command RENAME ""
  redis_sh: |
    #!/bin/bash
    while true;
    do
        ping -c 1 redis
        if [ $? -eq 0 ]
        then
            redis-server /redis-data/slave.conf
            break
        else
            if [[ ${HOSTNAME} == 'redis-0' ]]
            then
                redis-server /redis-data/master.conf
                break
            fi
        fi
    done