imagePullSecrets: registry-gitlab-key

sentinel:
  name: sentinel
  replicas: 3

redis:
  name: redis
  replicas: 1

ingress:
  host: devkluster.ehr.ee
  tlsSecret: redis-dev-cert

repository: __CI_REGISTRY_IMAGE__
imagePullPolicy: Always

redisConnectionSecret: redis-connection